services:

  php:
    build:
      context: .
      dockerfile: phpapache
    ports:
      - '8080:80'
    restart: always
    volumes:
      - ./:/var/www/html
      - ./default.conf:/etc/apache2/sites-available/000-default.conf

  mysql:
    image: mysql:5.7
    restart: always
    env_file:
      - '.env'
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    ports:
      - '3308:3306'
    volumes:
      - './db/mysql:/var/lib/mysql'