services:
  apache:
    container_name: apache
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - '80:80'
    volumes:
      - ./logs:/var/log/apache2
      - ./docker/apache-2.4.conf:/etc/apache2/sites-enabled/app.conf
      - ./docker/php.ini:/usr/local/etc/php/custom.ini
      - ./html:/var/www
    restart: always

  mysql:
    container_name: mysql
    image: mysql:5.7
    ports:
      - '3306:3306'
    env_file:
      - '.env'
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - './db/mysql:/var/lib/mysql'
    restart: always